# ─── Configurações da aplicação ───────────────────────────────────────────────
spring.application.name=livros-api
server.port=8080

# Formato de data/hora nas respostas JSON
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.serialization.indent-output=true
